//---------------------------------------------------------------------------
//
// Name:        SMEnums.h
// Author:      Gabriel Ferri
// Created:     02/10/2008
// Description: Definitions for the States Machine
//
//---------------------------------------------------------------------------
#ifndef __SMENUMS_H
#define __SMENUMS_H

enum SMEnum
{
	SM_NONE,
	SM_ALIGNMENT,
	SM_PRINTING,
	SM_VERIFY,
	SM_PLATEMOVEMENT,
	SM_CAMERAFOCUS,
	SM_CAMERASCALE,
	SM_CAMERAOFFSET,
	SM_CAMERAZERO,
	SM_HARDWARETEST,
	SM_VISION,
	SM_DEMOMODE,
	SM_CONVEDGE,
	SM_PINS,
	SM_INSPECTION,
	SM_VIEWRECORDS,
	SM_PASTE
};

enum AlignmentStateEnum
{
	ALIGNMENT_STATE_INIT0,
	ALIGNMENT_STATE_INIT1,
	ALIGNMENT_STATE_INIT2,
	ALIGNMENT_STATE_RESET,
	ALIGNMENT_STATE_MOVE_A,
	ALIGNMENT_STATE_TEACH_A,
	ALIGNMENT_STATE_SEARCH_A,
	ALIGNMENT_STATE_FOUND_A,
	ALIGNMENT_STATE_FOUND_WAIT_A,
	ALIGNMENT_STATE_ROT_A,
	ALIGNMENT_STATE_TRA_A,
	ALIGNMENT_STATE_VERIFY,
	ALIGNMENT_STATE_TEACH_VERIFY,
	ALIGNMENT_STATE_CHECK,
	ALIGNMENT_STATE_FID_MOVE,
	ALIGNMENT_STATE_FID_TEACH,
	ALIGNMENT_STATE_FID_SEARCH,
	ALIGNMENT_STATE_FID_FOUND,
	ALIGNMENT_STATE_FID_FOUND_WAIT,
	ALIGNMENT_STATE_LOWBORDER, //n.u.
	ALIGNMENT_STATE_LEFTBORDER,
	ALIGNMENT_STATE_DRAWBOARD,
	ALIGNMENT_STATE_SQUEEGEES_ZERO,
	ALIGNMENT_STATE_SQUEEGEES_ZERO_SAVE,
	ALIGNMENT_STATE_SQUEEGEES_MOVE,
	ALIGNMENT_STATE_SQUEEGEES_MOVE_SAVE,
	ALIGNMENT_STATE_MOVE_T2,
	ALIGNMENT_STATE_TEACH_T2,
	ALIGNMENT_STATE_SEARCH_T2,
	ALIGNMENT_STATE_FOUND_T2,
	ALIGNMENT_STATE_FOUND_WAIT_T2,
	ALIGNMENT_STATE_ROT_T2,
	ALIGNMENT_STATE_TRA_T2,
	ALIGNMENT_STATE_REVIEW_TEACH,
	ALIGNMENT_STATE_REVIEW_SEARCH,
	ALIGNMENT_STATE_REVIEW_NEXT,
	ALIGNMENT_STATE_AGAIN_SEARCH,
	ALIGNMENT_STATE_AGAIN_FOUND,
	ALIGNMENT_STATE_AGAIN_FOUND_WAIT,
	ALIGNMENT_STATE_AGAIN_NEXT
};

enum CameraZeroEnum
{
	CAMERAZERO_STATE_INIT0,
	CAMERAZERO_STATE_INIT,
	CAMERAZERO_STATE_RESET,
	CAMERAZERO_STATE_MOVE,
	CAMERAZERO_STATE_TEACH,
	CAMERAZERO_STATE_SEARCH,
	CAMERAZERO_STATE_FOUND,
	CAMERAZERO_STATE_FOUND_WAIT
};

enum PrintingStateEnum
{
	PRINTING_STATE_INIT1,
	PRINTING_STATE_INIT2,
	PRINTING_STATE_RESET,
	PRINTING_STATE_PRINT1,
	PRINTING_STATE_PRINT2,
	PRINTING_STATE_ALIGNPOS,
	PRINTING_STATE_SEARCH,
  	PRINTING_STATE_FOUND,
	PRINTING_STATE_FOUND_WAIT,
	PRINTING_STATE_ROT,
	PRINTING_STATE_ROT_CHECK, //Aggiunto per valutare errore di rotazione
	PRINTING_STATE_TRA,
	PRINTING_STATE_TRA_CHECK,
	PRINTING_STATE_NEXT,
	PRINTING_STATE_VERIFY,
	PRINTING_STATE_VERIFY_CAMERA,
	PRINTING_STATE_VERIFY_NEXT,
	PRINTING_STATE_VERIFY_PREV,
	PRINTING_STATE_CLEANING_CHECK,
	PRINTING_STATE_CLEANING,
	PRINTING_STATE_FINAL,
	PRINTING_STATE_STOP,
	PRINTING_STATE_CHOOSE,
	PRINTING_STATE_INSPECTION_MOVE,
	PRINTING_STATE_INSPECTION_WAIT,
	PRINTING_STATE_INSPECTION_CHECK,
	PRINTING_STATE_IDLE_PHASE1_DRAW,
	PRINTING_STATE_IDLE_PHASE1,
	PRINTING_STATE_IDLE_PHASE2_DRAW,
	PRINTING_STATE_IDLE_PHASE2,
	PRINTING_STATE_INSPECTION,
	PRINTING_STATE_INSPECTION_NEXT_MOVE,
	PRINTING_STATE_INSPECTION_NEXT,
	PRINTING_STATE_INSPECTION_PREV
};

enum VerifyStateEnum
{
	VERIFY_STATE_INIT,
	VERIFY_STATE_RESET,
	VERIFY_STATE_VERIFY,
	VERIFY_STATE_VERIFY_NEXT,
	VERIFY_STATE_VERIFY_PREV,
	VERIFY_STATE_FINAL
};

enum PinsStateEnum
{
	PINS_STATE_INIT,
	PINS_STATE_RESET,
	PINS_STATE_CHECKCOVER,
	PINS_STATE_WAITCOVER,
	PINS_STATE_SELECT,
	PINS_STATE_SELECT_NEXT,
	PINS_STATE_SELECT_PREV,
	PINS_STATE_FINAL
};

enum PasteConditioningStateEnum
{
	PASTE_STATE_INIT1,
	PASTE_STATE_INIT2,
	PASTE_STATE_RESET,
	PASTE_STATE_PRINT1,
	PASTE_STATE_PRINT2,
	PASTE_STATE_PRINT3,
	PASTE_STATE_DISENGAGE,
	PASTE_STATE_FINAL,
	PASTE_STATE_STOP
};


enum PlateMovementStateEnum
{
	PLATEMOVEMENT_STATE_INIT,
	PLATEMOVEMENT_STATE_RESET,
	PLATEMOVEMENT_STATE_FINAL
};

enum CameraFocusStateEnum
{
	CAMERAFOCUS_STATE_INIT,
	CAMERAFOCUS_STATE_RESET,
	CAMERAFOCUS_STATE_FINAL
};

enum CameraScaleStateEnum
{
	CAMERASCALE_STATE_INIT,
	CAMERASCALE_STATE_RESET,
	CAMERASCALE_STATE_MOVE,
	CAMERASCALE_STATE_X_START,
	CAMERASCALE_STATE_X_END,
	CAMERASCALE_STATE_X_SAVE,
	CAMERASCALE_STATE_Y_START,
	CAMERASCALE_STATE_Y_END,
	CAMERASCALE_STATE_Y_SAVE
};

enum CameraOffsetStateEnum
{
	CAMERAOFFSET_STATE_INIT,
	CAMERAOFFSET_STATE_RESET,
	CAMERAOFFSET_STATE_PRINTING,
	CAMERAOFFSET_STATE_MECH_OFFSET,
	CAMERAOFFSET_STATE_SEARCH,
  	CAMERAOFFSET_STATE_SEARCH_MATCH,
  	CAMERAOFFSET_STATE_SEARCH_TESTWAIT,
	CAMERAOFFSET_STATE_SEARCH_TESTUP,
 	CAMERAOFFSET_STATE_SEARCH_TESTUP_MATCH,
	CAMERAOFFSET_STATE_SEARCH_PARUP,
	CAMERAOFFSET_STATE_SEARCH_TESTDN,
 	CAMERAOFFSET_STATE_SEARCH_TESTDN_MATCH,
	CAMERAOFFSET_STATE_CHECK,
	CAMERAOFFSET_STATE_REVIEW_SEARCH,
 	CAMERAOFFSET_STATE_REVIEW_SEARCH_MATCH,
	CAMERAOFFSET_STATE_REVIEW_NEXT,
	CAMERAOFFSET_STATE_REVIEW_FOUND,
	CAMERAOFFSET_STATE_REVIEW_FOUND_WAIT,
	CAMERAOFFSET_STATE_REVIEW_ASK_MANUAL
};

enum VisionStateEnum
{
	VISION_STATE_INIT,
	VISION_STATE_RESET,
	VISION_STATE_MOVE,
	VISION_STATE_TEACH,
	VISION_STATE_SEARCH
};

enum DemomodeStateEnum
{
	DEMOMODE_STATE_INIT,
	DEMOMODE_STATE_RESET
};

enum ConveyorEdgeStateEnum
{
	CONVEDGE_STATE_INIT,
	CONVEDGE_STATE_RESET,
	CONVEDGE_STATE_FINAL
};

enum InspectionStateEnum
{
	INSPECTION_STATE_INIT,
	INSPECTION_STATE_SEARCH_A,
	INSPECTION_STATE_FOUND_A,
	INSPECTION_STATE_FOUND_WAIT_A,
	INSPECTION_STATE_ROT_A,
	INSPECTION_STATE_TRA_A,
	INSPECTION_STATE_NEXT_A,
	INSPECTION_STATE_MOVE,
	//INSPECTION_STATE_REFERENCE_MASK,
	//INSPECTION_STATE_REFERENCE_MASK_TEACH,
	INSPECTION_STATE_TEACH,
	INSPECTION_STATE_TEACH_FIND,
	INSPECTION_STATE_TEACH_DRAW,
	INSPECTION_STATE_TEACH_OK,
	INSPECTION_STATE_TEACH_CANCEL,
	INSPECTION_STATE_SET_THRESHOLD_START,
	INSPECTION_STATE_SET_THRESHOLD_END,
	INSPECTION_STATE_SET_THRESHOLD_DIALOG,
	INSPECTION_STATE_SET_THRESHOLD_CANCEL,
	INSPECTION_STATE_IDLE_FIND,
	INSPECTION_STATE_IDLE_DRAW,
	INSPECTION_STATE_RESET
};

#endif
