#ifndef WXSTATUSPANEL_H
#define WXSTATUSPANEL_H

//(*Headers(wxStatusPanel)
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/statline.h>
#include <wx/panel.h>
#include <wx/statbmp.h>
#include <wx/timer.h>
//*)

#include "SRMachine.h"
#include "SmartLog.h"

class wxStatusPanel: public wxPanel
{
	public:

		wxStatusPanel(wxWindow* parent,wxWindowID id=wxID_ANY,const wxPoint& pos=wxDefaultPosition,const wxSize& size=wxDefaultSize);
		virtual ~wxStatusPanel();

		//(*Declarations(wxStatusPanel)
		wxStaticBitmap* CamXStatus13;
		wxStaticBitmap* Table2Status2;
		wxStaticBitmap* CamYEncStatus2;
		wxStaticText* StaticText93;
		wxStaticText* StaticText79;
		wxStaticText* StaticText97;
		wxStaticText* StaticText101;
		wxStaticText* StaticText110;
		wxStaticBitmap* CamXStatus7;
		wxStaticText* StaticText75;
		wxStaticBitmap* PlateStatus16;
		wxStaticBitmap* LConvWStatus2;
		wxStaticBitmap* CamYStatus4;
		wxStaticText* StaticText68;
		wxStaticBitmap* Table2Status3;
		wxStaticText* StaticText100;
		wxStaticText* StaticText71;
		wxStaticText* StaticText32;
		wxStaticText* StaticText36;
		wxStaticBitmap* Table1Status3;
		wxStaticBitmap* PlateStatus11;
		wxStaticText* StaticText40;
		wxStaticText* StaticText112;
		wxStaticText* StaticText27;
		wxStaticText* StaticText89;
		wxStaticBitmap* SqueegeesStatus16;
		wxStaticBitmap* SqueegeesStatus9;
		wxStaticText* StaticText41;
		wxStaticBitmap* CamYStatus9;
		wxStaticBitmap* Table2Status4;
		wxStaticText* StaticText85;
		wxStaticBitmap* PlateStatus12;
		wxStaticBitmap* CamYStatus2;
		wxStaticText* StaticText50;
		wxStaticText* StaticText46;
		wxStaticBitmap* PlateStatus13;
		wxStaticBitmap* CamYStatus1;
		wxStaticText* StaticText72;
		wxStaticText* StaticText69;
		wxStaticBitmap* CamXStatus11;
		wxStaticText* StaticText64;
		wxStaticText* StaticText42;
		wxStaticText* StaticText73;
		wxStaticText* StaticText92;
		wxStaticText* StaticText48;
		wxStaticText* StaticText5;
		wxStaticText* StaticText87;
		wxStaticBitmap* CConvFStatus3;
		wxStaticBitmap* SqueegeesStatus5;
		wxStaticText* StaticText25;
		wxStaticText* StaticText6;
		wxStaticText* StaticText108;
		wxStaticBitmap* CamXEncStatus3;
		wxStaticBitmap* PlateStatus2;
		wxStaticText* StaticText52;
		wxStaticBitmap* CamXEncStatus1;
		wxStaticText* StaticText84;
		wxStaticBitmap* CamXStatus14;
		wxStaticBitmap* PlateStatus14;
		wxStaticText* StaticText19;
		wxStaticBitmap* CamYStatus7;
		wxStaticBitmap* SqueegeesStatus4;
		wxStaticBitmap* SqueegeesStatus12;
		wxStaticBitmap* PlateStatus5;
		wxStaticBitmap* LConvFStatus3;
		wxStaticText* StaticText39;
		wxStaticText* StaticText106;
		wxStaticText* StaticText10;
		wxStaticBitmap* CamYStatus3;
		wxStaticText* StaticText35;
		wxStaticBitmap* CamXStatus3;
		wxStaticBitmap* SqueegeesStatus1;
		wxStaticBitmap* CamYEncStatus3;
		wxStaticText* StaticText120;
		wxStaticBitmap* CamXStatus12;
		wxStaticBitmap* Table3Status1;
		wxStaticBitmap* CamYEncStatus4;
		wxStaticText* StaticText78;
		wxStaticBitmap* CamXStatus8;
		wxStaticBitmap* Table1Status2;
		wxStaticText* StaticText23;
		wxStaticText* StaticText33;
		wxStaticBitmap* CamXStatus10;
		wxStaticText* StaticText12;
		wxStaticText* StaticText22;
		wxStaticBitmap* CConvWStatus4;
		wxStaticText* StaticText76;
		wxStaticText* StaticText56;
		wxStaticBitmap* PlateEncStatus3;
		wxStaticBitmap* SqueegeesStatus13;
		wxStaticBitmap* PlateStatus1;
		wxStaticBitmap* Table1Status5;
		wxStaticBitmap* CamXEncStatus4;
		wxStaticText* StaticText90;
		wxStaticBitmap* PlateStatus9;
		wxStaticBitmap* SqueegeesStatus15;
		wxStaticLine* StaticLine3;
		wxStaticText* StaticText49;
		wxStaticBitmap* LConvWStatus3;
		wxStaticText* StaticText55;
		wxStaticText* StaticText109;
		wxStaticBitmap* CamXStatus4;
		wxStaticBitmap* Table3Status2;
		wxStaticBitmap* PlateStatus7;
		wxStaticText* StaticText99;
		wxStaticText* StaticText119;
		wxStaticBitmap* PlateEncStatus2;
		wxStaticText* StaticText61;
		wxStaticText* StaticText7;
		wxStaticBitmap* PlateStatus10;
		wxStaticBitmap* CamXStatus16;
		wxStaticBitmap* CamYStatus8;
		wxStaticText* StaticText16;
		wxStaticBitmap* CConvWStatus2;
		wxStaticBitmap* PlateStatus15;
		wxStaticText* StaticText107;
		wxStaticText* StaticText57;
		wxStaticLine* StaticLine1;
		wxStaticText* StaticText60;
		wxStaticBitmap* SqueegeesEncStatus2;
		wxStaticText* StaticText47;
		wxStaticText* StaticText98;
		wxStaticText* StaticText43;
		wxStaticText* StaticText24;
		wxStaticText* StaticText65;
		wxStaticBitmap* LConvFStatus1;
		wxStaticBitmap* SqueegeesStatus3;
		wxStaticText* StaticText94;
		wxStaticText* StaticText82;
		wxStaticText* StaticText14;
		wxStaticText* StaticText88;
		wxStaticBitmap* LConvWStatus4;
		wxStaticText* StaticText34;
		wxStaticBitmap* CamXStatus6;
		wxStaticText* StaticText70;
		wxStaticText* StaticText18;
		wxStaticBitmap* LoaderStatus3;
		wxStaticText* StaticText86;
		wxStaticBitmap* LConvWStatus1;
		wxStaticText* StaticText113;
		wxStaticBitmap* PlateEncStatus4;
		wxStaticBitmap* CamYEncStatus1;
		wxStaticBitmap* PlateStatus4;
		wxStaticText* StaticText105;
		wxStaticText* StaticText37;
		wxStaticText* StaticText13;
		wxStaticText* StaticText51;
		wxStaticText* StaticText117;
		wxStaticText* StaticText53;
		wxStaticBitmap* CConvWStatus1;
		wxStaticText* StaticText54;
		wxStaticText* StaticText20;
		wxStaticText* StaticText118;
		wxStaticBitmap* CamYStatus10;
		wxStaticBitmap* SqueegeesStatus2;
		wxStaticBitmap* Table2Status1;
		wxStaticBitmap* Table3Status3;
		wxStaticBitmap* CConvWStatus3;
		wxStaticText* StaticText31;
		wxStaticBitmap* LoaderStatus2;
		wxStaticBitmap* CamYStatus15;
		wxStaticText* StaticText103;
		wxStaticBitmap* CamYStatus11;
		wxStaticText* StaticText116;
		wxStaticBitmap* CamXStatus15;
		wxStaticBitmap* SqueegeesEncStatus3;
		wxStaticText* StaticText74;
		wxStaticBitmap* CConvFStatus2;
		wxStaticText* StaticText96;
		wxStaticBitmap* CConvFStatus4;
		wxStaticText* StaticText67;
		wxStaticText* StaticText104;
		wxStaticBitmap* CamYStatus12;
		wxStaticBitmap* PlateEncStatus1;
		wxStaticBitmap* CConvWStatus5;
		wxStaticText* StaticText45;
		wxStaticBitmap* CConvFStatus5;
		wxStaticBitmap* PlateStatus6;
		wxStaticBitmap* LConvFStatus4;
		wxStaticBitmap* SqueegeesStatus8;
		wxStaticBitmap* CamXStatus1;
		wxStaticText* StaticText62;
		wxStaticBitmap* CamXStatus5;
		wxStaticText* StaticText21;
		wxStaticText* StaticText4;
		wxStaticText* StaticText80;
		wxStaticBitmap* Table3Status5;
		wxStaticText* StaticText77;
		wxStaticText* StaticText114;
		wxStaticBitmap* CamYStatus14;
		wxStaticText* StaticText59;
		wxStaticBitmap* SqueegeesStatus14;
		wxStaticText* StaticText95;
		wxTimer statusTimer;
		wxStaticText* StaticText66;
		wxStaticLine* StaticLine5;
		wxStaticText* StaticText15;
		wxStaticText* StaticText26;
		wxStaticText* StaticText8;
		wxStaticText* StaticText28;
		wxStaticText* StaticText30;
		wxStaticText* StaticText29;
		wxStaticText* StaticText58;
		wxStaticBitmap* CConvFStatus1;
		wxStaticBitmap* LConvFStatus2;
		wxStaticBitmap* PlateStatus8;
		wxStaticBitmap* SqueegeesStatus10;
		wxStaticText* StaticText63;
		wxStaticBitmap* SqueegeesStatus7;
		wxStaticBitmap* SqueegeesStatus11;
		wxStaticBitmap* PlateStatus3;
		wxStaticBitmap* LConvFStatus5;
		wxStaticText* StaticText1;
		wxStaticText* StaticText2;
		wxStaticBitmap* CamYStatus16;
		wxStaticLine* StaticLine4;
		wxStaticBitmap* SqueegeesEncStatus1;
		wxStaticBitmap* LoaderStatus5;
		wxStaticText* StaticText83;
		wxStaticText* StaticText38;
		wxStaticBitmap* Table2Status5;
		wxStaticText* StaticText111;
		wxStaticText* StaticText91;
		wxStaticText* StaticText17;
		wxStaticText* StaticText115;
		wxStaticText* StaticText81;
		wxStaticText* StaticText102;
		wxStaticText* StaticText11;
		wxStaticBitmap* CamYStatus6;
		wxStaticBitmap* CamYStatus5;
		wxStaticBitmap* Table1Status1;
		wxStaticBitmap* Table3Status4;
		wxStaticBitmap* CamXStatus9;
		wxStaticBitmap* LConvWStatus5;
		wxStaticBitmap* SqueegeesStatus6;
		wxStaticBitmap* Table1Status4;
		wxStaticBitmap* CamXEncStatus2;
		wxStaticBitmap* SqueegeesEncStatus4;
		wxStaticBitmap* LoaderStatus4;
		wxStaticText* StaticText9;
		wxStaticBitmap* LoaderStatus1;
		wxStaticBitmap* CamYStatus13;
		wxStaticBitmap* CamXStatus2;
		wxStaticText* StaticText44;
		wxStaticText* StaticText3;
		//*)

	protected:

		//(*Identifiers(wxStatusPanel)
		static const long ID_STATICBITMAP17;
		static const long ID_STATICTEXT17;
		static const long ID_STATICBITMAP18;
		static const long ID_STATICTEXT18;
		static const long ID_STATICBITMAP19;
		static const long ID_STATICTEXT19;
		static const long ID_STATICBITMAP20;
		static const long ID_STATICTEXT20;
		static const long ID_STATICBITMAP21;
		static const long ID_STATICTEXT21;
		static const long ID_STATICBITMAP22;
		static const long ID_STATICTEXT22;
		static const long ID_STATICBITMAP23;
		static const long ID_STATICTEXT23;
		static const long ID_STATICBITMAP24;
		static const long ID_STATICTEXT24;
		static const long ID_STATICBITMAP25;
		static const long ID_STATICTEXT25;
		static const long ID_STATICBITMAP26;
		static const long ID_STATICTEXT26;
		static const long ID_STATICBITMAP27;
		static const long ID_STATICTEXT27;
		static const long ID_STATICBITMAP28;
		static const long ID_STATICTEXT28;
		static const long ID_STATICBITMAP29;
		static const long ID_STATICTEXT29;
		static const long ID_STATICBITMAP30;
		static const long ID_STATICTEXT30;
		static const long ID_STATICBITMAP31;
		static const long ID_STATICTEXT31;
		static const long ID_STATICBITMAP32;
		static const long ID_STATICTEXT32;
		static const long ID_STATICBITMAP84;
		static const long ID_STATICTEXT84;
		static const long ID_STATICBITMAP85;
		static const long ID_STATICTEXT85;
		static const long ID_STATICBITMAP86;
		static const long ID_STATICTEXT86;
		static const long ID_STATICBITMAP97;
		static const long ID_STATICTEXT97;
		static const long ID_STATICBITMAP101;
		static const long ID_STATICTEXT101;
		static const long ID_STATICBITMAP102;
		static const long ID_STATICTEXT102;
		static const long ID_STATICBITMAP103;
		static const long ID_STATICTEXT103;
		static const long ID_STATICBITMAP104;
		static const long ID_STATICTEXT104;
		static const long ID_STATICBITMAP105;
		static const long ID_STATICTEXT105;
		static const long ID_STATICBITMAP106;
		static const long ID_STATICTEXT106;
		static const long ID_STATICBITMAP107;
		static const long ID_STATICTEXT107;
		static const long ID_STATICBITMAP108;
		static const long ID_STATICTEXT108;
		static const long ID_STATICBITMAP109;
		static const long ID_STATICTEXT109;
		static const long ID_STATICBITMAP110;
		static const long ID_STATICTEXT110;
		static const long ID_STATICBITMAP111;
		static const long ID_STATICTEXT111;
		static const long ID_STATICBITMAP112;
		static const long ID_STATICTEXT112;
		static const long ID_STATICBITMAP113;
		static const long ID_STATICTEXT113;
		static const long ID_STATICBITMAP114;
		static const long ID_STATICTEXT114;
		static const long ID_STATICBITMAP115;
		static const long ID_STATICTEXT115;
		static const long ID_STATICBITMAP116;
		static const long ID_STATICTEXT116;
		static const long ID_STATICBITMAP117;
		static const long ID_STATICTEXT117;
		static const long ID_STATICBITMAP118;
		static const long ID_STATICTEXT118;
		static const long ID_STATICBITMAP119;
		static const long ID_STATICTEXT119;
		static const long ID_STATICBITMAP120;
		static const long ID_STATICTEXT120;
		static const long ID_STATICBITMAP1;
		static const long ID_STATICTEXT1;
		static const long ID_STATICBITMAP2;
		static const long ID_STATICTEXT2;
		static const long ID_STATICBITMAP3;
		static const long ID_STATICTEXT3;
		static const long ID_STATICBITMAP4;
		static const long ID_STATICTEXT4;
		static const long ID_STATICBITMAP5;
		static const long ID_STATICTEXT5;
		static const long ID_STATICBITMAP6;
		static const long ID_STATICTEXT6;
		static const long ID_STATICBITMAP7;
		static const long ID_STATICTEXT7;
		static const long ID_STATICBITMAP8;
		static const long ID_STATICTEXT8;
		static const long ID_STATICBITMAP9;
		static const long ID_STATICTEXT9;
		static const long ID_STATICBITMAP10;
		static const long ID_STATICTEXT10;
		static const long ID_STATICBITMAP11;
		static const long ID_STATICTEXT11;
		static const long ID_STATICBITMAP12;
		static const long ID_STATICTEXT12;
		static const long ID_STATICBITMAP13;
		static const long ID_STATICTEXT13;
		static const long ID_STATICBITMAP14;
		static const long ID_STATICTEXT14;
		static const long ID_STATICBITMAP15;
		static const long ID_STATICTEXT15;
		static const long ID_STATICBITMAP16;
		static const long ID_STATICTEXT16;
		static const long ID_STATICLINE1;
		static const long ID_STATICBITMAP81;
		static const long ID_STATICTEXT81;
		static const long ID_STATICBITMAP82;
		static const long ID_STATICTEXT82;
		static const long ID_STATICBITMAP83;
		static const long ID_STATICTEXT83;
		static const long ID_STATICBITMAP96;
		static const long ID_STATICTEXT96;
		static const long ID_STATICBITMAP33;
		static const long ID_STATICTEXT33;
		static const long ID_STATICBITMAP34;
		static const long ID_STATICTEXT34;
		static const long ID_STATICBITMAP35;
		static const long ID_STATICTEXT35;
		static const long ID_STATICBITMAP36;
		static const long ID_STATICTEXT36;
		static const long ID_STATICBITMAP37;
		static const long ID_STATICTEXT37;
		static const long ID_STATICBITMAP38;
		static const long ID_STATICTEXT38;
		static const long ID_STATICBITMAP39;
		static const long ID_STATICTEXT39;
		static const long ID_STATICBITMAP40;
		static const long ID_STATICTEXT40;
		static const long ID_STATICBITMAP41;
		static const long ID_STATICTEXT41;
		static const long ID_STATICBITMAP42;
		static const long ID_STATICTEXT42;
		static const long ID_STATICBITMAP43;
		static const long ID_STATICTEXT43;
		static const long ID_STATICBITMAP44;
		static const long ID_STATICTEXT44;
		static const long ID_STATICBITMAP45;
		static const long ID_STATICTEXT45;
		static const long ID_STATICBITMAP46;
		static const long ID_STATICTEXT46;
		static const long ID_STATICBITMAP47;
		static const long ID_STATICTEXT47;
		static const long ID_STATICBITMAP48;
		static const long ID_STATICTEXT48;
		static const long ID_STATICLINE3;
		static const long ID_STATICBITMAP87;
		static const long ID_STATICTEXT87;
		static const long ID_STATICBITMAP88;
		static const long ID_STATICTEXT88;
		static const long ID_STATICBITMAP89;
		static const long ID_STATICTEXT89;
		static const long ID_STATICBITMAP98;
		static const long ID_STATICTEXT98;
		static const long ID_STATICBITMAP49;
		static const long ID_STATICTEXT49;
		static const long ID_STATICBITMAP50;
		static const long ID_STATICTEXT50;
		static const long ID_STATICBITMAP51;
		static const long ID_STATICTEXT51;
		static const long ID_STATICBITMAP52;
		static const long ID_STATICTEXT52;
		static const long ID_STATICBITMAP53;
		static const long ID_STATICTEXT53;
		static const long ID_STATICBITMAP54;
		static const long ID_STATICTEXT54;
		static const long ID_STATICBITMAP55;
		static const long ID_STATICTEXT55;
		static const long ID_STATICBITMAP56;
		static const long ID_STATICTEXT56;
		static const long ID_STATICBITMAP57;
		static const long ID_STATICTEXT57;
		static const long ID_STATICBITMAP58;
		static const long ID_STATICTEXT58;
		static const long ID_STATICBITMAP59;
		static const long ID_STATICTEXT59;
		static const long ID_STATICBITMAP60;
		static const long ID_STATICTEXT60;
		static const long ID_STATICBITMAP61;
		static const long ID_STATICTEXT61;
		static const long ID_STATICBITMAP62;
		static const long ID_STATICTEXT62;
		static const long ID_STATICBITMAP63;
		static const long ID_STATICTEXT63;
		static const long ID_STATICBITMAP64;
		static const long ID_STATICTEXT64;
		static const long ID_STATICLINE4;
		static const long ID_STATICBITMAP90;
		static const long ID_STATICTEXT90;
		static const long ID_STATICBITMAP91;
		static const long ID_STATICTEXT91;
		static const long ID_STATICBITMAP92;
		static const long ID_STATICTEXT92;
		static const long ID_STATICBITMAP99;
		static const long ID_STATICTEXT99;
		static const long ID_STATICBITMAP65;
		static const long ID_STATICTEXT65;
		static const long ID_STATICBITMAP66;
		static const long ID_STATICTEXT66;
		static const long ID_STATICBITMAP67;
		static const long ID_STATICTEXT67;
		static const long ID_STATICBITMAP68;
		static const long ID_STATICTEXT68;
		static const long ID_STATICBITMAP69;
		static const long ID_STATICTEXT69;
		static const long ID_STATICBITMAP70;
		static const long ID_STATICTEXT70;
		static const long ID_STATICBITMAP71;
		static const long ID_STATICTEXT71;
		static const long ID_STATICBITMAP72;
		static const long ID_STATICTEXT72;
		static const long ID_STATICBITMAP73;
		static const long ID_STATICTEXT73;
		static const long ID_STATICBITMAP74;
		static const long ID_STATICTEXT74;
		static const long ID_STATICBITMAP75;
		static const long ID_STATICTEXT75;
		static const long ID_STATICBITMAP76;
		static const long ID_STATICTEXT76;
		static const long ID_STATICBITMAP77;
		static const long ID_STATICTEXT77;
		static const long ID_STATICBITMAP78;
		static const long ID_STATICTEXT78;
		static const long ID_STATICBITMAP79;
		static const long ID_STATICTEXT79;
		static const long ID_STATICBITMAP80;
		static const long ID_STATICTEXT80;
		static const long ID_STATICLINE5;
		static const long ID_STATICBITMAP93;
		static const long ID_STATICTEXT93;
		static const long ID_STATICBITMAP94;
		static const long ID_STATICTEXT94;
		static const long ID_STATICBITMAP95;
		static const long ID_STATICTEXT95;
		static const long ID_STATICBITMAP100;
		static const long ID_STATICTEXT100;
		static const long ID_TIMER1;
		//*)

	private:

		//(*Handlers(wxStatusPanel)
		void OnPaint(wxPaintEvent& event);
		void OnstatusTimerTrigger(wxTimerEvent& event);
		//*)

	public:
		int Init( SRMachine* SRRef, SmartLog* smartLoggerRef );
		int ShowControl();
		int HideControl();

	private:
		
		static const long ID_STATUS_TIMER;

		SRMachine *SR;
		SmartLog *smartLogger;

		bool isTimerBusy;

		int plateStatus;
		int squeegeesStatus;
		int camXStatus;
		int camYStatus;
		int table1Status;
		int table2Status;
		int table3Status;
		int lConvWStatus;
		int lConvFStatus;
		int cConvWStatus;
		int cConvFStatus;
		int loaderStatus;
		
		int plateEncStatus;
		int squeegeesEncStatus;
		int camXEncStatus;
		int camYEncStatus;

		DECLARE_EVENT_TABLE()
};

#endif
